### ISSUE TITLE
Teste SPA Angular

### ISSUE THREAD

**Issue by GuilhermeFerrariNeto** [FieldControl/valinor#169]

**Comment by lfreneda** [comment]
@GuilhermeFerrariNeto olá?

**Comment by caiorsantanna** [comment]
@GuilhermeFerrariNeto Beleza? Acho que o que você queria fazer é abrir um PR para a gente avaliar o seu teste, para isso, siga esse tutorial do próprio github:
https://docs.github.com/pt/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Vou fechar essa issue tudo bem? Qualquer duvida, me contate por email: caio.santanna@fieldcontrol.com.br
